### ISSUE TITLE
run with LoRA Block Weight  will cause it unavailable

### ISSUE THREAD

**Issue by youjiyouji01** [a2569875/stable-diffusion-webui-composable-lora#2]
run with LoRA Block Weight  will cause it unavailable. I want use like  <lora:my:1:1,0,0,0,0,0,0,0,1,1,1,0,0,0,0,0,0>.went I do it ,Both plugins will unavailable.The output image did not include LORA
我想分層控制LORA，當我輸入例如<lora:my:1:1,0,0,0,0,0,0,0,1,1,1,0,0,0,0,0,0>的提示詞後，分層控制LORA與可自主LORA都失效，會輸出成沒有加入LORA的原圖，如何解决在使用本挿件的基礎上可以分層控制LORA呢？

**Comment by a2569875** [comment]
@youjiyouji01 我調整了一下演算方式，你更新一下擴展，看看問題有沒有解決。 感謝

**Comment by youjiyouji01** [comment]
@a2569875 問題解决了，挿件可以一起使用了，真的十分感謝
