### ISSUE TITLE
[功能請求]請求對sd-webui-regional-prompter插件的相容

### ISSUE THREAD

**Issue by cuffuuguu** [a2569875/stable-diffusion-webui-composable-lora#22]
# 環境：
- windows11
- chrome
- A1111 webUI [68f336b](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/68f336bd994bed5442ad95bad6b6ad5564a5409a)
- sd-webui-regional-prompter [e656235](https://github.com/hako-mikan/sd-webui-regional-prompter/commit/e656235614b1827bf00a164ead964ecc071b7f56)
- a03d40eb3a3bc63728f46f1c00229310734c8fef

# 問題描述：
同時開啟regional-prompter和composable-lora時，當利用\<lora:model\>語法使用模型時，lora會失效（不論其實際上是lora或是lycoris）。而單獨關閉其中一個，又能確認lora有生效。

在您的插件仍然相容lycoris插件時，透過\<lyco:model\>語法是能夠 **正常** 將regional-prompter和composable-lora一起使用的，不過當時\<lora:model\>語法也會失效。

我認為可以透過同時使用regional-prompter和composable-lora並嘗試使用任何lora來復現此問題。

# 請求理由

1. regional-prompter在某些場合下能表現得比latent-couple插件好，圖片品質更好。
2. 先前透過\<lyco:model\>語法能將您的插件正常地與regional-prompter一同使用，所以解決上述問題可能不涉及到顛覆性的改動。
3. 即使在圖片品質相同的情況下，regional-prompter也提供更方便的介面與使用方式。

希望您能採納這個意見，因為您的插件成品相當優秀，感謝您的付出、貢獻與努力，若能提供對regional-prompter插件的相容，我相信會變得更好。

# 問題範例：

A 幾週前，使用webUI 1.4.0(composable-lora仍支援lycoris時)，將regional-prompter和composable-lora一起使用生成的圖片，可以看出lycoris工作正常：
![00053-718927907](https://github.com/a2569875/stable-diffusion-webui-composable-lora/assets/119902881/38fb580c-e7fc-4e01-8b6c-f3e8434ed539)

B 與A相同的描述、種子，webUI 1.5，把描述中的\<lyco:model\>改為\<lora:model\>，可以觀察到lora失效，人物特徵丟失：
![00204-718927907](https://github.com/a2569875/stable-diffusion-webui-composable-lora/assets/119902881/5c04f47e-f30f-4de1-8bc3-66ac75e07aba)

C 與B相同，但關閉regional-prompter，lora應該還有生效：
![00219-718927907](https://github.com/a2569875/stable-diffusion-webui-composable-lora/assets/119902881/2120677f-0fb2-4a14-aa3d-0c889da1bed4)

D 與B相同，但關閉composable-lora，lora應該還有生效，但混雜在一起：
![00209-718927907](https://github.com/a2569875/stable-diffusion-webui-composable-lora/assets/119902881/7b4d24e1-ef71-41a5-9bed-63704185a49d)

由ABCD總結推測，同時使用regional-prompter和composable-lora會使所有以\<lora:model\>調用的模型失效，希望您可以提供對regional-prompter的相容，辛苦了。

**Comment by alphaply** [comment]
1.5.1不用lyc插件

**Comment by alphaply** [comment]
请使用latent couple+composable lora

**Comment by cuffuuguu** [comment]
> 请使用latent couple+composable lora

我知道，我會用，但我是希望不僅對latent couple，也對regional-prompter相容。

我也知道現在不再需要lycoris插件，提出來只是因為可能對於兼容上的工作有幫助。

這是一個對新功能的請求，我知道正常情況下這個插件怎麼使用，謝謝。

**Comment by alphaply** [comment]
latent couple可以自定义mask区域
