### ISSUE TITLE
Request for Compatibility with a1111-sd-webui-lycoris

### ISSUE THREAD

**Issue by jimlin1668478052** [a2569875/stable-diffusion-webui-composable-lora#7]
a1111-sd-webui-lycoris (https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris) by KohakuBlueleaf is a package to support lycoris and locon to be used in a1111. Different from a1111-sd-webui-locon which is replaced by it, a1111-sd-webui-lycoris uses a new format <lyco:name:...> to incorporate the lycoris, rather than <lora:...>. Is it possible to make the <lyco> format supported in composable-lora? Thanks.

**Comment by a2569875** [comment]
Can't work? I remember that I have the implementation corresponding function.
[9010ce1: Add support for \<lyco:MODEL\> syntax](https://github.com/a2569875/stable-diffusion-webui-composable-lora/commit/9010ce1ba0d24d551aab21bf5f6e88bd2df6c08d)

**Comment by jimlin1668478052** [comment]
I tried again.
It seems that the <lyco> format does not work.

Prompt: original, masterpiece, extremely detailed CG unity 8k wallpaper, highlight, best quality, 2girls,
AND original, masterpiece, extremely detailed CG unity 8k wallpaper, highlight, best quality, 2girls, <lyco:symboli_kris_s_loha:0.8>, symboli kris s \(umamusume\), high collar, shoulder armor, black gloves, white ascot, clothing cutout, cleavage cutout, crop top, shirt, gold trim, cropped jacket, green jacket, open clothes, long sleeves, navel, midriff, black belt, green shorts, short shorts, thigh strap, closed mouth, serious,
AND original, masterpiece, extremely detailed CG unity 8k wallpaper, highlight, best quality, 2girls,   <lyco:tap_dance_city_loha:0.7>,  tap dance city \(umamusume\), ear ornament, jewelry, detached sleeves, sleeveless dress, bare shoulders, red gloves, off shoulder, clothing cutout, halterneck, striped, crop top, red shirt, bodice, white skirt, very long skirt, black pantyhose,

Negative prompt: (easynegative:0.8)

lycoris: https://civitai.com/models/75037/tap-dance-city-umamusume, https://civitai.com/models/25566?modelVersionId=30612

Loading LoRA step controller...
========================================
Apply LyCORIS model: symboli_kris_s_loha
Text encoder weight: 0.8
Unet weight: 0.8
DyLoRA Dim: None
========================================
Apply LyCORIS model: tap_dance_city_loha
Text encoder weight: 0.7
Unet weight: 0.7
DyLoRA Dim: None
========================================
Couldn't find Lora with name symboli_kris_s_loha
Couldn't find Lora with name tap_dance_city_loha
Composable LoRA load successful.
100% 45/45 [01:40<00:00,  2.23s/it]

The images are not similar to the anime characters of those lycoris.

**Comment by a2569875** [comment]
your console has this text "Couldn't find Lora with name symboli_kris_s_loha"
did you put the loha file in your lycoris Folder?

**Comment by jimlin1668478052** [comment]
Okay. It seems to be where the problem is. I will put them into this folder and try again.

**Comment by jimlin1668478052** [comment]
The issue solved now.
